[PAGE_LAYOUT]
AUTOSCALE=0
USE_PRINTAREA_MARGIN=0
IMAGE_FIELD1_FRAME=0
TEXT_FIELDS=0
DRAW_RECTS=0
COLUMNS=12
ROWS=12
UNITISINCH=0
LEFT_MARGIN=2
TOP_MARGIN=2
COLUMN_SPACE=0
ROW_SPACE=0

[LABEL_LAYOUT]
IMAGE_FIELD1_RESOLUTION=0
IMAGE_FIELDS=0
DRAW_RECTS=0
WIDTH=1
HEIGHT=1
FRAME_LABEL=0
SHOW_IMAGE=1
FRAME_IMAGE=0
IMAGE_USE_REAL_SIZE=0
IMAGE_AUTO_ROTATE=0
IMAGE_USE_CROP=0
IMAGE_LEFT=0.0
IMAGE_TOP=0.0
IMAGE_RIGHT=1
IMAGE_BOTTOM=1
IMAGE_RESOLUTION=50
TEXT_FIELDS=0

[INFO]
DESCRIPTION=CD-Cover 12x12.